'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SezioniDocumentiEventi

    '''<summary>
    '''updSEZIONIDOCEVENTI_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updSEZIONIDOCEVENTI_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdSEZIONIDOCEVENTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdSEZIONIDOCEVENTI As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsSEZIONIDOCEVENTI_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsSEZIONIDOCEVENTI_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updSEZIONIDOCEVENTI_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updSEZIONIDOCEVENTI_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''frmSEZIONIDOCEVENTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmSEZIONIDOCEVENTI As Global.Softailor.Web.UI.DbForms.StlFormView

    '''<summary>
    '''sdsSEZIONIDOCEVENTI_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsSEZIONIDOCEVENTI_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
End Class
