'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CategorieBinari
    
    '''<summary>
    '''updCATEGO_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updCATEGO_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''grdCATEGO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCATEGO As Global.Softailor.Web.UI.DbForms.StlGridView
    
    '''<summary>
    '''sdsCATEGO_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsCATEGO_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''updCATEGO_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updCATEGO_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''frmCATEGO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmCATEGO As Global.Softailor.Web.UI.DbForms.StlFormView
    
    '''<summary>
    '''sdsCATEGO_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsCATEGO_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''updFORCAT_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updFORCAT_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''grdFORCAT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdFORCAT As Global.Softailor.Web.UI.DbForms.StlGridView
    
    '''<summary>
    '''sdsFORCAT_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsFORCAT_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''updFORCAT_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updFORCAT_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''frmFORCAT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmFORCAT As Global.Softailor.Web.UI.DbForms.StlFormView
    
    '''<summary>
    '''sdsFORCAT_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsFORCAT_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
End Class
