'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditProfile

    '''<summary>
    '''updContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updContent As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlStep1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStep1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ac_CODICEFISCALE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_CODICEFISCALE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''err_ac_CODICEFISCALE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_ac_CODICEFISCALE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ac_TITOLO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_TITOLO As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''err_ac_TITOLO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_ac_TITOLO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tx_COGNOME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_COGNOME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''err_tx_COGNOME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_tx_COGNOME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tx_NOME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_NOME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''err_tx_NOME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_tx_NOME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dt_NASCITA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dt_NASCITA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''err_dt_NASCITA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_dt_NASCITA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ac_PROVINCIA_nascita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_PROVINCIA_nascita As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''err_ac_PROVINCIA_nascita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_ac_PROVINCIA_nascita As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ac_LUOGO_nascita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_LUOGO_nascita As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''err_ac_LUOGO_nascita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_ac_LUOGO_nascita As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ac_GENERE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_GENERE As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''err_ac_GENERE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_ac_GENERE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tx_INDIRIZZO_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_INDIRIZZO_res As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''err_tx_INDIRIZZO_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_tx_INDIRIZZO_res As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ac_PROVINCIA_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_PROVINCIA_res As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''err_ac_PROVINCIA_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_ac_PROVINCIA_res As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ac_COMUNE_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_COMUNE_res As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''err_ac_COMUNE_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_ac_COMUNE_res As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ac_CAP_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_CAP_res As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''err_ac_CAP_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_ac_CAP_res As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tx_TELEFONO_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_TELEFONO_res As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''err_tx_TELEFONO_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_tx_TELEFONO_res As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tx_FAX_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_FAX_res As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''err_tx_FAX_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_tx_FAX_res As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tx_CELLULARE_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_CELLULARE_res As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''err_tx_CELLULARE_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_tx_CELLULARE_res As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tx_EMAILPEC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_EMAILPEC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''err_tx_EMAILPEC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_tx_EMAILPEC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ac_CATEGORIALAVORATIVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_CATEGORIALAVORATIVA As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''err_ac_CATEGORIALAVORATIVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_ac_CATEGORIALAVORATIVA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ac_RUOLO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_RUOLO As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''err_ac_RUOLO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_ac_RUOLO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ac_PROFILO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_PROFILO As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''err_ac_PROFILO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_ac_PROFILO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlac_CODICEESTERNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlac_CODICEESTERNO As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_ac_CODICEESTERNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ac_CODICEESTERNO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ac_CODICEESTERNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_CODICEESTERNO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''err_ac_CODICEESTERNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_ac_CODICEESTERNO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''id_DISCIPLINA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_DISCIPLINA As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''err_id_DISCIPLINA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_id_DISCIPLINA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tx_ENTE_lav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_ENTE_lav As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''err_tx_ENTE_lav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_tx_ENTE_lav As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tx_INDIRIZZO_lav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_INDIRIZZO_lav As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''err_tx_INDIRIZZO_lav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_tx_INDIRIZZO_lav As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ac_PROVINCIA_lav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_PROVINCIA_lav As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''err_ac_PROVINCIA_lav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_ac_PROVINCIA_lav As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ac_COMUNE_lav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_COMUNE_lav As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''err_ac_COMUNE_lav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_ac_COMUNE_lav As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ac_CAP_lav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_CAP_lav As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''err_ac_CAP_lav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_ac_CAP_lav As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkNext1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNext1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''errStep1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errStep1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlStep2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStep2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''r_ac_CODICEFISCALE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_ac_CODICEFISCALE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_tx_TITOLO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_TITOLO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_tx_COGNOME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_COGNOME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_tx_NOME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_NOME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_dt_NASCITA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_dt_NASCITA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_ac_PROVINCIA_nascita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_ac_PROVINCIA_nascita As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_ac_LUOGO_nascita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_ac_LUOGO_nascita As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_tx_GENERE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_GENERE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_tx_INDIRIZZO_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_INDIRIZZO_res As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_tx_CAP_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_CAP_res As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_tx_COMUNE_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_COMUNE_res As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_tx_PROVINCIA_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_PROVINCIA_res As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_tx_TELEFONO_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_TELEFONO_res As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_tx_FAX_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_FAX_res As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_tx_CELLULARE_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_CELLULARE_res As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_tx_EMAILPEC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_EMAILPEC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_tx_CATEGORIALAVORATIVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_CATEGORIALAVORATIVA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_tx_RUOLO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_RUOLO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_tx_PROFILO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_PROFILO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnl_r_ac_CODICEESTERNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_r_ac_CODICEESTERNO As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_r_ac_CODICEESTERNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_r_ac_CODICEESTERNO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_ac_CODICEESTERNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_ac_CODICEESTERNO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_tx_DISCIPLINA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_DISCIPLINA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_tx_ENTE_lav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_ENTE_lav As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_tx_INDIRIZZO_lav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_INDIRIZZO_lav As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_tx_CAP_lav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_CAP_lav As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_tx_COMUNE_lav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_COMUNE_lav As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''r_tx_PROVINCIA_lav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_PROVINCIA_lav As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkPrevious2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPrevious2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkConfirm As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''errStep5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errStep5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlStep3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStep3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''sdsac_TITOLO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_TITOLO As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsac_PROVINCIA_nascita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_PROVINCIA_nascita As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsac_LUOGO_nascita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_LUOGO_nascita As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsac_PROVINCIA_indirizzo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_PROVINCIA_indirizzo As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsac_COMUNE_indirizzo_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_COMUNE_indirizzo_res As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsac_CAP_indirizzo_res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_CAP_indirizzo_res As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsac_CATEGORIALAVORATIVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_CATEGORIALAVORATIVA As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsac_RUOLO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_RUOLO As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsac_PROFILO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_PROFILO As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsid_DISCIPLINA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsid_DISCIPLINA As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsac_COMUNE_indirizzo_lav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_COMUNE_indirizzo_lav As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsac_CAP_indirizzo_lav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_CAP_indirizzo_lav As Global.System.Web.UI.WebControls.SqlDataSource
End Class
