'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EventDetail
    
    '''<summary>
    '''updEvento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updEvento As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''phdEvento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phdEvento As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''updIscrizioneEvento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updIscrizioneEvento As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''phdIscrizione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phdIscrizione As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''updPopupIscrizioneEvento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPopupIscrizioneEvento As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''phdPopupIscrizione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phdPopupIscrizione As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''login_lnk_login_sso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents login_lnk_login_sso As Global.System.Web.UI.WebControls.LinkButton
End Class
