'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FormazioneIndividuale
    
    '''<summary>
    '''updOpen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updOpen As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lnkOpenEmptyForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkOpenEmptyForm As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''updPending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPending As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''phdPending control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phdPending As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''updForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updForm As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''id_PARTECIPAZIONE_in control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_PARTECIPAZIONE_in As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''id_PARTECIPAZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_PARTECIPAZIONE As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''ni_ANNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ni_ANNO As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''ni_NUMERO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ni_NUMERO As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblPopupTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPopupTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlDataEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDataEntry As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblStep1Title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStep1Title As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ac_CATEGORIAECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_CATEGORIAECM As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''err_ac_CATEGORIAECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_ac_CATEGORIAECM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tx_TITOLO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_TITOLO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''err_tx_TITOLO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_tx_TITOLO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ac_TIPOLOGIAEVENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_TIPOLOGIAEVENTO As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''err_ac_TIPOLOGIAEVENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_ac_TIPOLOGIAEVENTO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlDatiFAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDatiFAD As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''dt_INIZIOFRUIZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dt_INIZIOFRUIZIONE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''err_dt_INIZIOFRUIZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_dt_INIZIOFRUIZIONE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dt_FINEFRUIZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dt_FINEFRUIZIONE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''err_dt_FINEFRUIZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_dt_FINEFRUIZIONE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ni_ORE_FAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ni_ORE_FAD As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ni_MINUTI_FAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ni_MINUTI_FAD As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''err_ni_ORE_FAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_ni_ORE_FAD As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlDatiNonFAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDatiNonFAD As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tx_SEDE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_SEDE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''err_tx_SEDE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_tx_SEDE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dt_INIZIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dt_INIZIO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''err_dt_INIZIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_dt_INIZIO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dt_FINE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dt_FINE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''err_dt_FINE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_dt_FINE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ni_ORE_RES control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ni_ORE_RES As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ni_MINUTI_RES control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ni_MINUTI_RES As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''err_ni_ORE_RES control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_ni_ORE_RES As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ac_STATOVERIFICAAPPRENDIMENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_STATOVERIFICAAPPRENDIMENTO As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''err_ac_STATOVERIFICAAPPRENDIMENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_ac_STATOVERIFICAAPPRENDIMENTO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlDatiEcm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDatiEcm As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ac_NORMATIVAECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_NORMATIVAECM As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''err_ac_NORMATIVAECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_ac_NORMATIVAECM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlCreditiConseguiti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCreditiConseguiti As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ac_STATOECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_STATOECM As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''err_ac_STATOECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_ac_STATOECM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlNumeroCrediti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNumeroCrediti As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''nd_CREDITIECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nd_CREDITIECM As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''err_nd_CREDITIECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_nd_CREDITIECM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlDataCrediti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDataCrediti As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''dt_OTTENIMENTOCREDITIECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dt_OTTENIMENTOCREDITIECM As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''err_dt_OTTENIMENTOCREDITIECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_dt_OTTENIMENTOCREDITIECM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkNext1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNext1 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlVerifyData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlVerifyData As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''r_tx_CATEGORIAECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_CATEGORIAECM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''r_tx_TITOLO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_TITOLO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''r_tx_TIPOLOGIAEVENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_TIPOLOGIAEVENTO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''r_pnlDatiFAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_pnlDatiFAD As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''r_dt_INIZIOFRUIZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_dt_INIZIOFRUIZIONE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''r_dt_FINEFRUIZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_dt_FINEFRUIZIONE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''r_ni_MINUTI_FAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_ni_MINUTI_FAD As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''r_pnlDatiNonFAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_pnlDatiNonFAD As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''r_tx_SEDE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_SEDE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''r_dt_INIZIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_dt_INIZIO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''r_dt_FINE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_dt_FINE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''r_ni_MINUTI_RES control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_ni_MINUTI_RES As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''r_tx_STATOVERIFICAAPPRENDIMENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_STATOVERIFICAAPPRENDIMENTO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''r_pnlDatiEcm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_pnlDatiEcm As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''r_tx_NORMATIVAECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_NORMATIVAECM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''r_pnlCreditiConseguiti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_pnlCreditiConseguiti As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''r_tx_STATOECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_tx_STATOECM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''r_pnlNumeroCrediti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_pnlNumeroCrediti As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''r_nd_CREDITIECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_nd_CREDITIECM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''r_pnlDataCrediti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_pnlDataCrediti As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''r_dt_OTTENIMENTOCREDITIECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents r_dt_OTTENIMENTOCREDITIECM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkNext2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNext2 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkPrevious2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPrevious2 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnlPrintForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPrintForm As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblPrintIstruzioni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrintIstruzioni As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkStampaAutocertificazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkStampaAutocertificazione As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''sdsac_CATEGORIAECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_CATEGORIAECM As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsac_TIPOLOGIAEVENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_TIPOLOGIAEVENTO As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsac_STATOVERIFICAAPPRENDIMENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_STATOVERIFICAAPPRENDIMENTO As Global.System.Web.UI.WebControls.SqlDataSource
End Class
