'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SelettorePersonaGForm

    '''<summary>
    '''ltrTitolo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrTitolo As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''updsrcPERSONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updsrcPERSONE As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''srcPERSONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcPERSONE As Global.Softailor.Web.UI.DbForms.StlSearchForm

    '''<summary>
    '''updPERSONE_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPERSONE_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdPERSONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPERSONE As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsPERSONE_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsPERSONE_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
End Class
