'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FormazioneEsterna
    
    '''<summary>
    '''ltrRepositioning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrRepositioning As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''updHiddenCtls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updHiddenCtls As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lnkReposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkReposition As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtReposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReposition As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''updsrcPARTECIPAZIONI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updsrcPARTECIPAZIONI As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''srcPARTECIPAZIONI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcPARTECIPAZIONI As Global.Softailor.Web.UI.DbForms.StlSearchForm
    
    '''<summary>
    '''updPARTECIPAZIONI_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPARTECIPAZIONI_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''grdPARTECIPAZIONI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPARTECIPAZIONI As Global.Softailor.Web.UI.DbForms.StlGridView
    
    '''<summary>
    '''sdsPARTECIPAZIONI_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsPARTECIPAZIONI_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''phdPulsantiNuovo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phdPulsantiNuovo As Global.System.Web.UI.WebControls.PlaceHolder
End Class
