'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Partecipazione
    
    '''<summary>
    '''ltrScripts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrScripts As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''updDati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updDati As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''hid_id_PARTECIPAZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hid_id_PARTECIPAZIONE As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hid_ac_TIPOPARTECIPAZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hid_ac_TIPOPARTECIPAZIONE As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hid_fl_GIORNIORE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hid_fl_GIORNIORE As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''trCreazioneModifica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trCreazioneModifica As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''lblCreazioneModifica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreazioneModifica As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tx_TIPOPARTECIPAZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_TIPOPARTECIPAZIONE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblNumeroData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumeroData As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ni_PARTECIPAZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ni_PARTECIPAZIONE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSpazioNumeroData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpazioNumeroData As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dt_PARTECIPAZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dt_PARTECIPAZIONE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errdt_PARTECIPAZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errdt_PARTECIPAZIONE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''id_PERSONA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_PERSONA As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''fl_PROFILOECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fl_PROFILOECM As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkPickPersona control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPickPersona As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''tx_PERSONA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_PERSONA As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlTipoContrattoKo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlTipoContrattoKo As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''errtx_PERSONA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errtx_PERSONA As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ac_UNITAOPERATIVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_UNITAOPERATIVA As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''err_ac_UNITAOPERATIVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_ac_UNITAOPERATIVA As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dt_INIZIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dt_INIZIO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''dt_FINE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dt_FINE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlPartParallele control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPartParallele As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''errdt_INIZIOFINE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errdt_INIZIOFINE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''id_PERSONA_RESPONSABILE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_PERSONA_RESPONSABILE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkPickResponsabile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPickResponsabile As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''tx_PERSONA_RESPONSABILE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_PERSONA_RESPONSABILE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errtx_PERSONA_RESPONSABILE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errtx_PERSONA_RESPONSABILE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ac_RESPONSABILE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_RESPONSABILE As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''ac_PROGETTOATTIVITA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_PROGETTOATTIVITA As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''ac_CONTRATTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_CONTRATTO As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''ac_CODICEPRAF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_CODICEPRAF As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errac_CODICEPRAF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errac_CODICEPRAF As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ac_CODICECUP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_CODICECUP As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errac_CODICECUP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errac_CODICECUP As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''id_EVENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_EVENTO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkPickEvento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPickEvento As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''tx_TITOLO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_TITOLO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errtx_TITOLO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errtx_TITOLO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ac_TIPOLOGIAEVENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_TIPOLOGIAEVENTO As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errac_TIPOLOGIAEVENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errac_TIPOLOGIAEVENTO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ac_TIPOCOBDETT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_TIPOCOBDETT As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errac_TIPOCOBDETT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errac_TIPOCOBDETT As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tx_SEDE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_SEDE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errtx_SEDE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errtx_SEDE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ac_NAZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_NAZIONE As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errac_NAZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errac_NAZIONE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tx_ORGANIZZATORE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_ORGANIZZATORE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errtx_ORGANIZZATORE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errtx_ORGANIZZATORE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tx_NOTEDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_NOTEDATE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errtx_NOTEDATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errtx_NOTEDATE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tr_GIORNIFORMAZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_GIORNIFORMAZIONE As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''nd_GIORNIFORMAZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nd_GIORNIFORMAZIONE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errnd_GIORNIFORMAZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errnd_GIORNIFORMAZIONE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tr_OREFORMAZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_OREFORMAZIONE As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''nd_OREFORMAZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nd_OREFORMAZIONE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errnd_OREFORMAZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errnd_OREFORMAZIONE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''nd_QUOTAISCRIZIONE_PREV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nd_QUOTAISCRIZIONE_PREV As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''nd_QUOTAISCRIZIONE_PREV_VALUTA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nd_QUOTAISCRIZIONE_PREV_VALUTA As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errnd_QUOTAISCRIZIONE_PREV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errnd_QUOTAISCRIZIONE_PREV As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''errnd_QUOTAISCRIZIONE_PREV_VALUTA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errnd_QUOTAISCRIZIONE_PREV_VALUTA As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dt_PAGARSIENTRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dt_PAGARSIENTRO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''err_dt_PAGARSIENTRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents err_dt_PAGARSIENTRO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''fl_ANTICIPOQUOTAISCRIZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fl_ANTICIPOQUOTAISCRIZIONE As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''tr_CIGQUOTAISCRIZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_CIGQUOTAISCRIZIONE As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''ac_CIGQUOTAISCRIZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_CIGQUOTAISCRIZIONE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errac_CIGQUOTAISCRIZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errac_CIGQUOTAISCRIZIONE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''nd_GIORNIVIAGGIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nd_GIORNIVIAGGIO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errnd_GIORNIVIAGGIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errnd_GIORNIVIAGGIO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''nd_COSTOVIAGGIO_PREV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nd_COSTOVIAGGIO_PREV As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errnd_COSTOVIAGGIO_PREV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errnd_COSTOVIAGGIO_PREV As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tx_CENTROCOSTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_CENTROCOSTO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tx_CENTROCOSTO_COMMESSA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_CENTROCOSTO_COMMESSA As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tr_EVENTOECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_EVENTOECM As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''fl_EVENTOECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fl_EVENTOECM As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''id_ELEME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_ELEME As Global.Softailor.SiteTailorIzs.UnboundBinaryElementBox
    
    '''<summary>
    '''pnlValdazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlValdazione As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ac_STATOPARTECIPAZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_STATOPARTECIPAZIONE As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tblDatiConsuntivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblDatiConsuntivo As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''nd_QUOTAISCRIZIONE_CONS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nd_QUOTAISCRIZIONE_CONS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errnd_QUOTAISCRIZIONE_CONS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errnd_QUOTAISCRIZIONE_CONS As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''nd_COSTOVIAGGIO_CONS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nd_COSTOVIAGGIO_CONS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errnd_COSTOVIAGGIO_CONS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errnd_COSTOVIAGGIO_CONS As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tr_CREDITIECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_CREDITIECM As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''nd_CREDITIECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nd_CREDITIECM As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errnd_CREDITIECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errnd_CREDITIECM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tr_OTTENIMENTOCREDITIECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr_OTTENIMENTOCREDITIECM As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''dt_OTTENIMENTOCREDITIECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dt_OTTENIMENTOCREDITIECM As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errdt_OTTENIMENTOCREDITIECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errdt_OTTENIMENTOCREDITIECM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSave As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''sdsac_UNITAOPERATIVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_UNITAOPERATIVA As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsac_TIPOLOGIAEVENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_TIPOLOGIAEVENTO As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsac_TIPOCOBDETT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_TIPOCOBDETT As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsac_NAZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_NAZIONE As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsac_STATOPARTECIPAZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_STATOPARTECIPAZIONE As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsac_CONTRATTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_CONTRATTO As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsnd_QUOTAISCRIZIONE_PREV_VALUTA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsnd_QUOTAISCRIZIONE_PREV_VALUTA As Global.System.Web.UI.WebControls.SqlDataSource
End Class
