'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CriteriAccesso
    
    '''<summary>
    '''ltrRepositioning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrRepositioning As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''updHiddenCtls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updHiddenCtls As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lnkRefreshCriteri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRefreshCriteri As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''updDati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updDati As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''iol_dt_INIZIOVISIBILITA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents iol_dt_INIZIOVISIBILITA As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''mediol_dt_INIZIOVISIBILITA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mediol_dt_INIZIOVISIBILITA As Global.AjaxControlToolkit.MaskedEditExtender
    
    '''<summary>
    '''erriol_dt_INIZIOVISIBILITA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents erriol_dt_INIZIOVISIBILITA As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''iol_dt_APERTURAISCRIZIONI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents iol_dt_APERTURAISCRIZIONI As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''mediol_dt_APERTURAISCRIZIONI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mediol_dt_APERTURAISCRIZIONI As Global.AjaxControlToolkit.MaskedEditExtender
    
    '''<summary>
    '''erriol_dt_APERTURAISCRIZIONI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents erriol_dt_APERTURAISCRIZIONI As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''iol_dt_CHIUSURAISCRIZIONI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents iol_dt_CHIUSURAISCRIZIONI As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''mediol_dt_CHIUSURAISCRIZIONI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mediol_dt_CHIUSURAISCRIZIONI As Global.AjaxControlToolkit.MaskedEditExtender
    
    '''<summary>
    '''erriol_dt_CHIUSURAISCRIZIONI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents erriol_dt_CHIUSURAISCRIZIONI As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''iol_ni_MAXPARTECIPANTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents iol_ni_MAXPARTECIPANTI As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''erriol_ni_MAXPARTECIPANTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents erriol_ni_MAXPARTECIPANTI As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkSaveHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSaveHeader As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''updCriteri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updCriteri As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''phdCriteri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phdCriteri As Global.System.Web.UI.WebControls.PlaceHolder
End Class
