'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GestioneAttestatiPartecipazioneOnLine
    
    '''<summary>
    '''updDati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updDati As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lnkAnteprimaPartecipante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAnteprimaPartecipante As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkAnteprimaDRMT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAnteprimaDRMT As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txttx_ATTPART_HAPART control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttx_ATTPART_HAPART As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkSavetxttx_ATTPART_HAPART control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSavetxttx_ATTPART_HAPART As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblNumPartecipantiInterni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumPartecipantiInterni As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNumPartecipantiEsterni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumPartecipantiEsterni As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNumDRMTInterni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumDRMTInterni As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNumDRMTEsterni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumDRMTEsterni As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkPI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPI As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPE As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkPIT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPIT As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkPET control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPET As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkDRMTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDRMTI As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkDRMTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDRMTE As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lnkSalva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSalva As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''cnfSalva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnfSalva As Global.AjaxControlToolkit.ConfirmButtonExtender
    
    '''<summary>
    '''phdRiepiloghi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phdRiepiloghi As Global.System.Web.UI.WebControls.PlaceHolder
End Class
