'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MailAttestatiPartecipazioneOnLine
    
    '''<summary>
    '''updContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updContent As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblListaAttivi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblListaAttivi As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNumPartecipantiInterni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumPartecipantiInterni As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNumPartecipantiEsterni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumPartecipantiEsterni As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNumPartecipantiInterniTest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumPartecipantiInterniTest As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNumPartecipantiEsterniTest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumPartecipantiEsterniTest As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNumDRMTInterni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumDRMTInterni As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNumDRMTEsterni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumDRMTEsterni As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''phdRiepiloghiToDo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phdRiepiloghiToDo As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lblStatoInvio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatoInvio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlSpacer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSpacer1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlWarningInvia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlWarningInvia As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlSpacer2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSpacer2 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lnkInvia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkInvia As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cnfInvia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnfInvia As Global.AjaxControlToolkit.ConfirmButtonExtender
    
    '''<summary>
    '''pnlSpacer3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSpacer3 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlWarning2invia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlWarning2invia As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlSpacer4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSpacer4 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblRisultatoInvio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRisultatoInvio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''phdRiepiloghiDone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phdRiepiloghiDone As Global.System.Web.UI.WebControls.PlaceHolder
End Class
