'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MailChiusuraListe

    '''<summary>
    '''updContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updContent As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblNumIscrittiConfermaImmediata control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumIscrittiConfermaImmediata As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNumAccettatiChiusuraListe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumAccettatiChiusuraListe As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNumNonAccettati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumNonAccettati As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNumDRM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumDRM As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''phdRiepiloghiToDo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phdRiepiloghiToDo As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''lblStatoInvio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatoInvio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlSpacer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSpacer1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlWarningInvia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlWarningInvia As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlSpacer2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSpacer2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlPrimoInvio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPrimoInvio As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkInviaA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInviaA As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkInviaB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInviaB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkInviaC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInviaC As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkInviaD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInviaD As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lnkInvia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkInvia As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cnfInvia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnfInvia As Global.AjaxControlToolkit.ConfirmButtonExtender

    '''<summary>
    '''pnlSpacer3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSpacer3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlWarning2invia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlWarning2invia As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlSpacer4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSpacer4 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblRisultatoInvio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRisultatoInvio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''phdRiepiloghiDone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phdRiepiloghiDone As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''tblReinvio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblReinvio As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''chkReInviaA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkReInviaA As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkReInviaB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkReInviaB As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkReInviaC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkReInviaC As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkReInviaD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkReInviaD As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lnkReinvia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkReinvia As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cnfReinvia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnfReinvia As Global.AjaxControlToolkit.ConfirmButtonExtender
End Class
