'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditorFiltro

    '''<summary>
    '''ltrLoadParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrLoadParent As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''updButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updButtons As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''sezioneAttEcm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sezioneAttEcm As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkSaveClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSaveClose As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''updLoadParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updLoadParent As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lnkLoadParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLoadParent As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtParentXml control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtParentXml As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''phdContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phdContent As Global.System.Web.UI.WebControls.PlaceHolder
End Class
