'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MailReportMP

    '''<summary>
    '''updMAILREPORTS_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updMAILREPORTS_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdMAILREPORTS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdMAILREPORTS As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsMAILREPORTS_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsMAILREPORTS_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updGenerazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updGenerazione As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hidid_MAILREPORT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidid_MAILREPORT As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pnlGenerazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGenerazione As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlFiltri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFiltri As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rblFiltroNone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblFiltroNone As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''phdControlliFiltri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phdControlliFiltri As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''rbFiltroPers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbFiltroPers As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''spanEditFiltro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spanEditFiltro As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''xmlFiltroPers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents xmlFiltroPers As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''phdControlliFonte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phdControlliFonte As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''lnkIniziaSpedizione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkIniziaSpedizione As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''sd_ac_FONTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_ac_FONTE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_id_MAILREPORT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_id_MAILREPORT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_tx_VALOREFILTROBASE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_tx_VALOREFILTROBASE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_xm_FILTRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_xm_FILTRO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_ac_ORDINAMENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_ac_ORDINAMENTO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_tx_ORDINAMENTO1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_tx_ORDINAMENTO1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_tx_ORDINAMENTO2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_tx_ORDINAMENTO2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_tx_ORDINAMENTO3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_tx_ORDINAMENTO3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_tx_ORDINAMENTO4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_tx_ORDINAMENTO4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_tx_ORDINAMENTO5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_tx_ORDINAMENTO5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_ragionesociale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_ragionesociale As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_indirizzocompleto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_indirizzocompleto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_tel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_tel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_fax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_email As Global.System.Web.UI.WebControls.TextBox
End Class
