'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ModelliMailReport

    '''<summary>
    '''updFONTI_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updFONTI_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdFONTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdFONTI As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsFONTI_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsFONTI_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updMAILREPORTS_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updMAILREPORTS_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdMAILREPORTS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdMAILREPORTS As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsMAILREPORTS_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsMAILREPORTS_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updMAILREPORTS_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updMAILREPORTS_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''frmMAILREPORTS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmMAILREPORTS As Global.Softailor.Web.UI.DbForms.StlFormView

    '''<summary>
    '''sdsMAILREPORTS_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsMAILREPORTS_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updUrl As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtModelsRelativeUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModelsRelativeUrl As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sdsac_ORDINAMENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_ORDINAMENTO As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''sdsid_FILTRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsid_FILTRO As Global.System.Web.UI.WebControls.SqlDataSource
End Class
