'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ReportQualitaApprendimento

    '''<summary>
    '''ddnAnno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddnAnno As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnValutazioniEventi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnValutazioniEventi As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnValutazioniEventiDocenti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnValutazioniEventiDocenti As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnValutazioniDocentiEventi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnValutazioniDocentiEventi As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnValutazioniDocenti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnValutazioniDocenti As Global.System.Web.UI.WebControls.LinkButton
End Class
