'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SpedizioneMailStep2

    '''<summary>
    '''updDatiGenerazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updDatiGenerazione As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''sd_ac_FONTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_ac_FONTE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_id_MAILREPORT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_id_MAILREPORT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_tx_VALOREFILTROBASE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_tx_VALOREFILTROBASE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_xm_FILTRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_xm_FILTRO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_ac_ORDINAMENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_ac_ORDINAMENTO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_tx_ORDINAMENTO1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_tx_ORDINAMENTO1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_tx_ORDINAMENTO2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_tx_ORDINAMENTO2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_tx_ORDINAMENTO3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_tx_ORDINAMENTO3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_tx_ORDINAMENTO4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_tx_ORDINAMENTO4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_tx_ORDINAMENTO5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_tx_ORDINAMENTO5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_ragionesociale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_ragionesociale As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_indirizzocompleto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_indirizzocompleto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_tel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_tel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_fax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_tx_OGGETTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_tx_OGGETTO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sd_ht_CORPO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sd_ht_CORPO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''updLista control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updLista As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''phdLista control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phdLista As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''updComandi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updComandi As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lnkSpedizione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSpedizione As Global.System.Web.UI.WebControls.LinkButton
End Class
