'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CentriReferenza

    '''<summary>
    '''updCENTRIREFERENZA_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updCENTRIREFERENZA_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdCENTRIREFERENZA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCENTRIREFERENZA As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsCENTRIREFERENZA_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsCENTRIREFERENZA_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updCENTRIREFERENZA_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updCENTRIREFERENZA_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''frmCENTRIREFERENZA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmCENTRIREFERENZA As Global.Softailor.Web.UI.DbForms.StlFormView

    '''<summary>
    '''sdsCENTRIREFERENZA_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsCENTRIREFERENZA_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
End Class
