'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Delibere

    '''<summary>
    '''updsrcDELIBERE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updsrcDELIBERE As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''srcDELIBERE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcDELIBERE As Global.Softailor.Web.UI.DbForms.StlSearchForm

    '''<summary>
    '''updDELIBERE_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updDELIBERE_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdDELIBERE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdDELIBERE As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsDELIBERE_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsDELIBERE_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updDELIBERE_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updDELIBERE_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''frmDELIBERE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmDELIBERE As Global.Softailor.Web.UI.DbForms.StlFormView

    '''<summary>
    '''sdsDELIBERE_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsDELIBERE_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''sdsac_TIPOLOGIADELIBERA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_TIPOLOGIADELIBERA As Global.System.Web.UI.WebControls.SqlDataSource
End Class
