'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Organizzatori

    '''<summary>
    '''updORGANIZZATORI_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updORGANIZZATORI_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdORGANIZZATORI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdORGANIZZATORI As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsORGANIZZATORI_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsORGANIZZATORI_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updORGANIZZATORI_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updORGANIZZATORI_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''frmORGANIZZATORI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmORGANIZZATORI As Global.Softailor.Web.UI.DbForms.StlFormView

    '''<summary>
    '''sdsORGANIZZATORI_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsORGANIZZATORI_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updRAPPRLEGALI_ORGANIZZATORI_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updRAPPRLEGALI_ORGANIZZATORI_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdRAPPRLEGALI_ORGANIZZATORI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdRAPPRLEGALI_ORGANIZZATORI As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsRAPPRLEGALI_ORGANIZZATORI_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsRAPPRLEGALI_ORGANIZZATORI_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updRAPPRLEGALI_ORGANIZZATORI_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updRAPPRLEGALI_ORGANIZZATORI_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''frmRAPPRLEGALI_ORGANIZZATORI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmRAPPRLEGALI_ORGANIZZATORI As Global.Softailor.Web.UI.DbForms.StlFormView

    '''<summary>
    '''sdsRAPPRLEGALI_ORGANIZZATORI_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsRAPPRLEGALI_ORGANIZZATORI_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''sdsac_TITOLO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_TITOLO As Global.System.Web.UI.WebControls.SqlDataSource
End Class
