'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Persona
    
    '''<summary>
    '''updButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updButtons As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lnkClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkClose As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkDownload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDownload As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ltrRepositioning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrRepositioning As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''updHiddenCtls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updHiddenCtls As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lnkRepositionAutocertificazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRepositionAutocertificazione As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkRepositionPartecipazione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRepositionPartecipazione As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkRepositionIscritto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRepositionIscritto As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtReposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReposition As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtRepositionEvento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRepositionEvento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''updPERSONE_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPERSONE_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''frmPERSONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmPERSONE As Global.Softailor.Web.UI.DbForms.StlFormView
    
    '''<summary>
    '''tabContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabContainer As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''pnlPortfolio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPortfolio As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''updPORTFOLIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPORTFOLIO As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''grdPORTFOLIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPORTFOLIO As Global.Softailor.Web.UI.DbForms.StlGridView
    
    '''<summary>
    '''pnlRecapiti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRecapiti As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''updRECAPITI_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updRECAPITI_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''grdRECAPITI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdRECAPITI As Global.Softailor.Web.UI.DbForms.StlGridView
    
    '''<summary>
    '''updRECAPITI_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updRECAPITI_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''frmRECAPITI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmRECAPITI As Global.Softailor.Web.UI.DbForms.StlFormView
    
    '''<summary>
    '''pnlStoricoRL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStoricoRL As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''updSTORICOLAVORATIVO_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updSTORICOLAVORATIVO_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''grdSTORICOLAVORATIVO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdSTORICOLAVORATIVO As Global.Softailor.Web.UI.DbForms.StlGridView
    
    '''<summary>
    '''sdsSTORICOLAVORATIVO_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsSTORICOLAVORATIVO_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''pnlRuoliAziendali control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRuoliAziendali As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''updRUOLI_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updRUOLI_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''grdRUOLI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdRUOLI As Global.Softailor.Web.UI.DbForms.StlGridView
    
    '''<summary>
    '''updRUOLI_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updRUOLI_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''frmRUOLI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmRUOLI As Global.Softailor.Web.UI.DbForms.StlFormView
    
    '''<summary>
    '''pnlPasswordReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPasswordReset As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''updPasswordReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPasswordReset As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lnkPasswordReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPasswordReset As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''cnfReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnfReset As Global.AjaxControlToolkit.ConfirmButtonExtender
    
    '''<summary>
    '''txtPasswordResetResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPasswordResetResult As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnlPortfolioDocente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPortfolioDocente As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''updPORTFOLIODOCENTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPORTFOLIODOCENTE As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''grdPORTFOLIODOCENTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPORTFOLIODOCENTE As Global.Softailor.Web.UI.DbForms.StlGridView
    
    '''<summary>
    '''sdsPERSONE_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsPERSONE_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''sdsRECAPITI_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsRECAPITI_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''sdsPORTFOLIO_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsPORTFOLIO_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''sdsRECAPITI_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsRECAPITI_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''sdsPORTFOLIODOCENTE_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsPORTFOLIODOCENTE_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''sdsRUOLI_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsRUOLI_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''sdsRUOLI_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsRUOLI_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''sdsac_TITOLO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_TITOLO As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsac_CATEGORIALAVORATIVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_CATEGORIALAVORATIVA As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsac_RUOLO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_RUOLO As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsid_ALBO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsid_ALBO As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsac_TIPORECAPITO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_TIPORECAPITO As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsac_RUOLOCOB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_RUOLOCOB As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsac_UNITAOPERATIVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_UNITAOPERATIVA As Global.System.Web.UI.WebControls.SqlDataSource
End Class
