'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProviderEcm

    '''<summary>
    '''updPROVIDERECM_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPROVIDERECM_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdPROVIDERECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPROVIDERECM As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsPROVIDERECM_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsPROVIDERECM_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updPROVIDERECM_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPROVIDERECM_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''frmPROVIDERECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmPROVIDERECM As Global.Softailor.Web.UI.DbForms.StlFormView

    '''<summary>
    '''sdsPROVIDERECM_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsPROVIDERECM_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updRAPPRLEGALI_PROVIDERECM_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updRAPPRLEGALI_PROVIDERECM_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdRAPPRLEGALI_PROVIDERECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdRAPPRLEGALI_PROVIDERECM As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsRAPPRLEGALI_PROVIDERECM_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsRAPPRLEGALI_PROVIDERECM_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updRAPPRLEGALI_PROVIDERECM_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updRAPPRLEGALI_PROVIDERECM_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''frmRAPPRLEGALI_PROVIDERECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmRAPPRLEGALI_PROVIDERECM As Global.Softailor.Web.UI.DbForms.StlFormView

    '''<summary>
    '''sdsRAPPRLEGALI_PROVIDERECM_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsRAPPRLEGALI_PROVIDERECM_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''sdsac_NORMATIVAECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_NORMATIVAECM As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsac_TITOLO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_TITOLO As Global.System.Web.UI.WebControls.SqlDataSource
End Class
