'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SediAule

    '''<summary>
    '''updSEDI_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updSEDI_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdSEDI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdSEDI As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsSEDI_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsSEDI_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updSEDI_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updSEDI_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''frmSEDI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmSEDI As Global.Softailor.Web.UI.DbForms.StlFormView

    '''<summary>
    '''sdsSEDI_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsSEDI_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updAULE_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updAULE_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdAULE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAULE As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsAULE_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsAULE_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updAULE_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updAULE_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''frmAULE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmAULE As Global.Softailor.Web.UI.DbForms.StlFormView

    '''<summary>
    '''sdsAULE_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsAULE_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
End Class
