'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TipologieDelibere

    '''<summary>
    '''updTIPOLOGIEDELIBERE_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updTIPOLOGIEDELIBERE_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdTIPOLOGIEDELIBERE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdTIPOLOGIEDELIBERE As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsTIPOLOGIEDELIBERE_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsTIPOLOGIEDELIBERE_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updTIPOLOGIEDELIBERE_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updTIPOLOGIEDELIBERE_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''frmTIPOLOGIEDELIBERE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmTIPOLOGIEDELIBERE As Global.Softailor.Web.UI.DbForms.StlFormView

    '''<summary>
    '''sdsTIPOLOGIEDELIBERE_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsTIPOLOGIEDELIBERE_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
End Class
