'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class VociSpesaRicavo

    '''<summary>
    '''updVOCISPESARICAVO_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updVOCISPESARICAVO_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdVOCISPESARICAVO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdVOCISPESARICAVO As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsVOCISPESARICAVO_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsVOCISPESARICAVO_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updVOCISPESARICAVO_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updVOCISPESARICAVO_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''frmVOCISPESARICAVO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmVOCISPESARICAVO As Global.Softailor.Web.UI.DbForms.StlFormView

    '''<summary>
    '''sdsVOCISPESARICAVO_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsVOCISPESARICAVO_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''sdsac_CATEGORIAECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_CATEGORIAECM As Global.System.Web.UI.WebControls.SqlDataSource
End Class
