'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public ReadOnly Property ErrorReportMailFrom() As String
            Get
                Return CType(Me("ErrorReportMailFrom"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public ReadOnly Property ErrorReportMailTo() As String
            Get
                Return CType(Me("ErrorReportMailTo"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PageTitle")>  _
        Public ReadOnly Property PageTitle() As String
            Get
                Return CType(Me("PageTitle"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("IZSLER")>  _
        Public ReadOnly Property CompanyKey() As String
            Get
                Return CType(Me("CompanyKey"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("IZSLER")>  _
        Public ReadOnly Property CompanyName_Short() As String
            Get
                Return CType(Me("CompanyName_Short"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PasswordResetKey")>  _
        Public ReadOnly Property PasswordResetKey() As String
            Get
                Return CType(Me("PasswordResetKey"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:64802/")>  _
        Public ReadOnly Property FrontOfficeUrl() As String
            Get
                Return CType(Me("FrontOfficeUrl"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GenericMail_RagioneSociale")>  _
        Public ReadOnly Property GenericMail_RagioneSociale() As String
            Get
                Return CType(Me("GenericMail_RagioneSociale"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GenericMail_IndirizzoCompleto")>  _
        Public ReadOnly Property GenericMail_IndirizzoCompleto() As String
            Get
                Return CType(Me("GenericMail_IndirizzoCompleto"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GenericMail_Tel")>  _
        Public ReadOnly Property GenericMail_Tel() As String
            Get
                Return CType(Me("GenericMail_Tel"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GenericMail_Fax")>  _
        Public ReadOnly Property GenericMail_Fax() As String
            Get
                Return CType(Me("GenericMail_Fax"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GenericMail_MailFrom")>  _
        Public ReadOnly Property GenericMail_MailFrom() As String
            Get
                Return CType(Me("GenericMail_MailFrom"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ValutazioneWeb_Key")>  _
        Public ReadOnly Property ValutazioneWeb_Key() As String
            Get
                Return CType(Me("ValutazioneWeb_Key"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ErrorReportMailSubject")>  _
        Public ReadOnly Property ErrorReportMailSubject() As String
            Get
                Return CType(Me("ErrorReportMailSubject"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ValutazioneWeb_Url")>  _
        Public ReadOnly Property ValutazioneWeb_Url() As String
            Get
                Return CType(Me("ValutazioneWeb_Url"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Program Files\LibreOffice\program\soffice.exe")>  _
        Public ReadOnly Property SofficeExePath() As String
            Get
                Return CType(Me("SofficeExePath"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("""C:/inetpub/temp/libreoffice""")>  _
        Public ReadOnly Property AppDataTempPath() As String
            Get
                Return CType(Me("AppDataTempPath"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public ReadOnly Property DEBUG_FLG() As String
            Get
                Return CType(Me("DEBUG_FLG"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public ReadOnly Property DEBUG_EMAIL_FROM() As String
            Get
                Return CType(Me("DEBUG_EMAIL_FROM"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public ReadOnly Property DEBUG_EMAIL_TO() As String
            Get
                Return CType(Me("DEBUG_EMAIL_TO"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Documents/GestioneFormazione/Modelli/Richieste_PartecipazioneExt/56B.002_rev02.do"& _ 
            "cx")>  _
        Public ReadOnly Property formazione_ext_path_56B_002() As String
            Get
                Return CType(Me("formazione_ext_path_56B_002"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Documents/GestioneFormazione/Modelli/Richieste_PartecipazioneExt/56C.002_rev02.do"& _ 
            "cx")>  _
        Public ReadOnly Property formazione_ext_path_56C_002() As String
            Get
                Return CType(Me("formazione_ext_path_56C_002"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Documents/GestioneFormazione/Modelli/Richieste_PartecipazioneExt/56D.002_rev02.do"& _ 
            "cx")>  _
        Public ReadOnly Property formazione_ext_path_56D_002() As String
            Get
                Return CType(Me("formazione_ext_path_56D_002"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("path assoluto a\BinaryData\AZI_1\")>  _
        Public ReadOnly Property BinariesBasePath() As String
            Get
                Return CType(Me("BinariesBasePath"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("path assoluto a\BinaryData")>  _
        Public ReadOnly Property BinariesBasePath_WoAzi() As String
            Get
                Return CType(Me("BinariesBasePath_WoAzi"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("path assoluto a\BackOffice\Reports")>  _
        Public ReadOnly Property ReportsBasePath() As String
            Get
                Return CType(Me("ReportsBasePath"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("path assoluto a cartella temporanea")>  _
        Public ReadOnly Property BinariesTmpBasePath() As String
            Get
                Return CType(Me("BinariesTmpBasePath"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.GestioneFormazione.FrontOffice.My.MySettings
            Get
                Return Global.GestioneFormazione.FrontOffice.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
