'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class menu

    '''<summary>
    '''updAPPLIC_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updAPPLIC_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdAPPLIC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAPPLIC As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsAPPLIC_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsAPPLIC_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updMENUBA_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updMENUBA_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdMENUBA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdMENUBA As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsMENUBA_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsMENUBA_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updMENUBA_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updMENUBA_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''frmMENUBA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmMENUBA As Global.Softailor.Web.UI.DbForms.StlFormView

    '''<summary>
    '''sdsMENUBA_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsMENUBA_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updMENUIT_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updMENUIT_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdMENUIT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdMENUIT As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsMENUIT_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsMENUIT_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updMENUIT_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updMENUIT_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''frmMENUIT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmMENUIT As Global.Softailor.Web.UI.DbForms.StlFormView

    '''<summary>
    '''sdsMENUIT_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsMENUIT_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
End Class
