'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AttribuzionePresenze
    
    '''<summary>
    '''updIscritti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updIscritti As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''grdIscritti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdIscritti As Global.Softailor.Web.UI.DbForms.StlGridView
    
    '''<summary>
    '''updMoveAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updMoveAll As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ddnMoveAll_Orig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddnMoveAll_Orig As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddnMoveAll_Dest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddnMoveAll_Dest As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lnkMoveAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkMoveAll As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''cnfMoveAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnfMoveAll As Global.AjaxControlToolkit.ConfirmButtonExtender
    
    '''<summary>
    '''updPresenti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPresenti As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''grdPresenti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPresenti As Global.Softailor.Web.UI.DbForms.StlGridView
    
    '''<summary>
    '''updPresentiParziali control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPresentiParziali As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''grdPresentiParziali control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPresentiParziali As Global.Softailor.Web.UI.DbForms.StlGridView
    
    '''<summary>
    '''updAssentiIngiustificati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updAssentiIngiustificati As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''grdAssentiIngiustificati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAssentiIngiustificati As Global.Softailor.Web.UI.DbForms.StlGridView
    
    '''<summary>
    '''updAssentiGiustificati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updAssentiGiustificati As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''grdAssentiGiustificati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAssentiGiustificati As Global.Softailor.Web.UI.DbForms.StlGridView
    
    '''<summary>
    '''sdsIscritti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsIscritti As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''sdsPresenti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsPresenti As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''sdsPresentiParziali control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsPresentiParziali As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''sdsAssentiIngiustificati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsAssentiIngiustificati As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''sdsAssentiGiustificati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsAssentiGiustificati As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
End Class
