'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CalcoloPresenze

    '''<summary>
    '''ltrRepositioning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrRepositioning As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''updHiddenCtls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updHiddenCtls As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lnkReposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkReposition As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtReposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReposition As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''updORARIEVENTO_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updORARIEVENTO_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdORARIEVENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdORARIEVENTO As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsORARIEVENTO_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsORARIEVENTO_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updTotale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updTotale As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblDurataTotale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDurataTotale As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''updEVENTO_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updEVENTO_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''frmEVENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmEVENTO As Global.Softailor.Web.UI.DbForms.StlFormView

    '''<summary>
    '''sdsEVENTO_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsEVENTO_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''updIscrittiKO_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updIscrittiKO_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdIscrittiKO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdIscrittiKO As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''updIscrittiOK_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updIscrittiOK_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdIscrittiOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdIscrittiOK As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsISCRITTIKO_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsISCRITTIKO_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''sdsISCRITTIOK_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsISCRITTIOK_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
End Class
