'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ConferimentoCreditiECM

    '''<summary>
    '''updCandidati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updCandidati As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdCandidati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCandidati As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''updMoveAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updMoveAll As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddnMoveAll_Orig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddnMoveAll_Orig As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddnMoveAll_Orig_Quest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddnMoveAll_Orig_Quest As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddnMoveAll_Orig_Presenza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddnMoveAll_Orig_Presenza As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddnMoveAll_Dest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddnMoveAll_Dest As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lnkMoveAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkMoveAll As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cnfMoveAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnfMoveAll As Global.AjaxControlToolkit.ConfirmButtonExtender

    '''<summary>
    '''updCreditiOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updCreditiOK As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdCreditiOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCreditiOK As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''updCreditiKO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updCreditiKO As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdCreditiKO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCreditiKO As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsCandidati control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsCandidati As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''sdsCreditiOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsCreditiOK As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''sdsCreditiKO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsCreditiKO As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
End Class
