'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ControlloAccessi

    '''<summary>
    '''updBarcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updBarcode As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlBarcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBarcode As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtBarcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBarcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnBarcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBarcode As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''updCognomeNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updCognomeNome As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlCognomeNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCognomeNome As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddnCognomeNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddnCognomeNome As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''updLetture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updLetture As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlLetture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLetture As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''l1id_accesso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l1id_accesso As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''l1id_iscritto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l1id_iscritto As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''l2id_accesso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l2id_accesso As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''l2id_iscritto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l2id_iscritto As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''l3id_accesso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l3id_accesso As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''l3id_iscritto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l3id_iscritto As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''l4id_accesso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l4id_accesso As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''l4id_iscritto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l4id_iscritto As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''l5id_accesso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l5id_accesso As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''l5id_iscritto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l5id_iscritto As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''l1name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l1name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''l1inout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l1inout As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''l1orario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l1orario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''l1delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l1delete As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cnf1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnf1 As Global.AjaxControlToolkit.ConfirmButtonExtender

    '''<summary>
    '''l1detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l1detail As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''l2name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l2name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''l2inout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l2inout As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''l2orario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l2orario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''l2delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l2delete As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cnf2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnf2 As Global.AjaxControlToolkit.ConfirmButtonExtender

    '''<summary>
    '''l2detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l2detail As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''l3name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l3name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''l3inout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l3inout As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''l3orario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l3orario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''l3delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l3delete As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cnf3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnf3 As Global.AjaxControlToolkit.ConfirmButtonExtender

    '''<summary>
    '''l3detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l3detail As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''l4name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l4name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''l4inout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l4inout As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''l4orario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l4orario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''l4delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l4delete As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cnf4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnf4 As Global.AjaxControlToolkit.ConfirmButtonExtender

    '''<summary>
    '''l4detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l4detail As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''l5name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l5name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''l5inout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l5inout As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''l5orario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l5orario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''l5delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l5delete As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cnf5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnf5 As Global.AjaxControlToolkit.ConfirmButtonExtender

    '''<summary>
    '''l5detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l5detail As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''updStatistiche control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updStatistiche As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlStatistiche control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStatistiche As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblIscritti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIscritti As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPresenti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPresenti As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAssenti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAssenti As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''updCognomeNomeManuale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updCognomeNomeManuale As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlCognomeNomeManuale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCognomeNomeManuale As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddnCognomeNomeManuale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddnCognomeNomeManuale As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''updUscitaGenerale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updUscitaGenerale As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlUscitaGenerale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlUscitaGenerale As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtUscitaGeneraleData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUscitaGeneraleData As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''medDATA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents medDATA As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''txtUscitaGeneraleOra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUscitaGeneraleOra As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''medINIZIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents medINIZIO As Global.AjaxControlToolkit.MaskedEditExtender

    '''<summary>
    '''btnRegistra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRegistra As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cnfUscita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnfUscita As Global.AjaxControlToolkit.ConfirmButtonExtender
End Class
