'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CorrezioneQuestionariApprendimento

    '''<summary>
    '''ltrRepositioning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrRepositioning As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''updHiddenCtls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updHiddenCtls As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lnkReposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkReposition As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtReposition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReposition As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''updNonCorretti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updNonCorretti As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdNonCorretti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdNonCorretti As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''updCorrettiOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updCorrettiOK As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdCorrettiOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCorrettiOK As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''updCorrettiKO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updCorrettiKO As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdCorrettiKO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCorrettiKO As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsNonCorretti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsNonCorretti As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''sdsCorrettiOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsCorrettiOK As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''sdsCorrettiKO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsCorrettiKO As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
End Class
