'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DuplicaEvento
    
    '''<summary>
    '''updContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updContent As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lbltx_TITOLO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltx_TITOLO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tx_TITOLO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_TITOLO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errtx_TITOLO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errtx_TITOLO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbltx_EDIZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltx_EDIZIONE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ac_EDIZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_EDIZIONE As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errac_EDIZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errac_EDIZIONE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbltx_SEDE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltx_SEDE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''id_SEDE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_SEDE As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errid_SEDE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errid_SEDE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbltx_DETTAGLISEDE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltx_DETTAGLISEDE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tx_DETTAGLISEDE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_DETTAGLISEDE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errtx_DETTAGLISEDE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errtx_DETTAGLISEDE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbldt_INIZIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldt_INIZIO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbldt_FINE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldt_FINE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dt_INIZIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dt_INIZIO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caldt_INIZIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caldt_INIZIO As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''meddt_INIZIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents meddt_INIZIO As Global.AjaxControlToolkit.MaskedEditExtender
    
    '''<summary>
    '''mevdt_INIZIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mevdt_INIZIO As Global.AjaxControlToolkit.MaskedEditValidator
    
    '''<summary>
    '''errdt_INIZIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errdt_INIZIO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dt_FINE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dt_FINE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caldt_FINE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caldt_FINE As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''meddt_FINE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents meddt_FINE As Global.AjaxControlToolkit.MaskedEditExtender
    
    '''<summary>
    '''mevdt_FINE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mevdt_FINE As Global.AjaxControlToolkit.MaskedEditValidator
    
    '''<summary>
    '''errdt_FINE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errdt_FINE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbltx_PIANOFORMATIVO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltx_PIANOFORMATIVO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''id_PIANOFORMATIVO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_PIANOFORMATIVO As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errid_PIANOFORMATIVO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errid_PIANOFORMATIVO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''orig_fl_NUOVOINPF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents orig_fl_NUOVOINPF As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''fl_NUOVOINPF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fl_NUOVOINPF As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''errfl_NUOVOINPF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errfl_NUOVOINPF As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''fl_COPIASPESERICAVIEVENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fl_COPIASPESERICAVIEVENTO As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''fl_COPIASPESERICAVIPERSONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fl_COPIASPESERICAVIPERSONE As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lnkDuplica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDuplica As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''cnfDuplica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnfDuplica As Global.AjaxControlToolkit.ConfirmButtonExtender
    
    '''<summary>
    '''lblGlobalError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGlobalError As Global.System.Web.UI.WebControls.Label
End Class
