'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GenerazioneRapportoEcmXml
    
    '''<summary>
    '''updEVENTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updEVENTI As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''frmEVENTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmEVENTI As Global.Softailor.Web.UI.DbForms.StlFormView
    
    '''<summary>
    '''phdRiassunto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phdRiassunto As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lnkGenera control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkGenera As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''sdsTFORM_EVE_SEC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsTFORM_EVE_SEC As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''sdsEVENTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsEVENTI As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
End Class
