'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class HomeEvento
    
    '''<summary>
    '''updDatiEventoEWorkFlow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updDatiEventoEWorkFlow As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''phdDatiEvento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phdDatiEvento As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''updIscritti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updIscritti As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''phdIscritti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phdIscritti As Global.System.Web.UI.WebControls.PlaceHolder
End Class
