'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NuovoPartecipante
    
    '''<summary>
    '''ltrScripts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrScripts As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''updPERSONE_src control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPERSONE_src As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''srcPERSONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcPERSONE As Global.Softailor.Web.UI.DbForms.StlSearchForm
    
    '''<summary>
    '''srcDOCENTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcDOCENTI As Global.Softailor.Web.UI.DbForms.StlSearchForm
    
    '''<summary>
    '''updPERSONE_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPERSONE_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''grdPERSONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPERSONE As Global.Softailor.Web.UI.DbForms.StlGridView
    
    '''<summary>
    '''grdDOCENTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdDOCENTI As Global.Softailor.Web.UI.DbForms.StlGridView
    
    '''<summary>
    '''sdsPERSONE_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsPERSONE_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''sdsDOCENTI_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsDOCENTI_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''lnkIscriviEsistente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkIscriviEsistente As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''updNuovo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updNuovo As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''pnlDatiNuovo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDatiNuovo As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ddnTitolo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddnTitolo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtCognome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCognome As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNome As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCodiceFiscale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodiceFiscale As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddnProfilo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddnProfilo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddnCategoriaLavorativa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddnCategoriaLavorativa As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''confirmBtnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents confirmBtnAdd As Global.AjaxControlToolkit.ConfirmButtonExtender
    
    '''<summary>
    '''lnkCreaIscriviNuovo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCreaIscriviNuovo As Global.System.Web.UI.WebControls.LinkButton
End Class
