'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NuovoEvento
    
    '''<summary>
    '''updContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updContent As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''tx_CODINT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_CODINT As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errtx_CODINT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errtx_CODINT As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''id_TIPOLOGIAEVENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_TIPOLOGIAEVENTO As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errid_TIPOLOGIAEVENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errid_TIPOLOGIAEVENTO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ac_TIPOCOBDETT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_TIPOCOBDETT As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errac_TIPOCOBDETT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errac_TIPOCOBDETT As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tx_TITOLO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_TITOLO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errtx_TITOLO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errtx_TITOLO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ac_EDIZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_EDIZIONE As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errac_EDIZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errac_EDIZIONE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''id_SEDE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_SEDE As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errid_SEDE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errid_SEDE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tx_DETTAGLISEDE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_DETTAGLISEDE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errtx_DETTAGLISEDE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errtx_DETTAGLISEDE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dt_INIZIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dt_INIZIO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caldt_INIZIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caldt_INIZIO As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''meddt_INIZIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents meddt_INIZIO As Global.AjaxControlToolkit.MaskedEditExtender
    
    '''<summary>
    '''mevdt_INIZIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mevdt_INIZIO As Global.AjaxControlToolkit.MaskedEditValidator
    
    '''<summary>
    '''errdt_INIZIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errdt_INIZIO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dt_FINE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dt_FINE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''caldt_FINE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents caldt_FINE As Global.AjaxControlToolkit.CalendarExtender
    
    '''<summary>
    '''meddt_FINE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents meddt_FINE As Global.AjaxControlToolkit.MaskedEditExtender
    
    '''<summary>
    '''mevdt_FINE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mevdt_FINE As Global.AjaxControlToolkit.MaskedEditValidator
    
    '''<summary>
    '''errdt_FINE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errdt_FINE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''id_ORGANIZZATORE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_ORGANIZZATORE As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errid_ORGANIZZATORE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errid_ORGANIZZATORE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''id_RAPPRLEGALE_ORGANIZZATORE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_RAPPRLEGALE_ORGANIZZATORE As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errid_RAPPRLEGALE_ORGANIZZATORE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errid_RAPPRLEGALE_ORGANIZZATORE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''id_SEGRETERIAORGANIZZATIVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_SEGRETERIAORGANIZZATIVA As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errid_SEGRETERIAORGANIZZATIVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errid_SEGRETERIAORGANIZZATIVA As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''id_CENTROREFERENZA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_CENTROREFERENZA As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errid_CENTROREFERENZA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errid_CENTROREFERENZA As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ac_CDC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_CDC As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errac_CDC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errac_CDC As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''id_PIANOFORMATIVO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_PIANOFORMATIVO As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errid_PIANOFORMATIVO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errid_PIANOFORMATIVO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''fl_NUOVOINPF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fl_NUOVOINPF As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''errfl_NUOVOINPF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errfl_NUOVOINPF As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tx_OBBIETTIVI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tx_OBBIETTIVI As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errtx_OBBIETTIVI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errtx_OBBIETTIVI As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ac_NORMATIVAECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_NORMATIVAECM As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''errac_NORMATIVAECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errac_NORMATIVAECM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlDatiEcm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDatiEcm As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''id_TIPOLOGIAECMEVENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_TIPOLOGIAECMEVENTO As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errid_TIPOLOGIAECMEVENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errid_TIPOLOGIAECMEVENTO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ecm2_TFORM_EVE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ecm2_TFORM_EVE As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errecm2_TFORM_EVE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errecm2_TFORM_EVE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''row_ecm2_TFORM_EVE_SEC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents row_ecm2_TFORM_EVE_SEC As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''ecm2_TFORM_EVE_SEC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ecm2_TFORM_EVE_SEC As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''errecm2_TFORM_EVE_SEC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errecm2_TFORM_EVE_SEC As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ecm2_TIPO_EVE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ecm2_TIPO_EVE As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errecm2_TIPO_EVE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errecm2_TIPO_EVE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ecm2_COD_OBI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ecm2_COD_OBI As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errecm2_COD_OBI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errecm2_COD_OBI As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ecm2_COD_ACCR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ecm2_COD_ACCR As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errecm2_COD_ACCR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errecm2_COD_ACCR As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''id_PROVIDERECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_PROVIDERECM As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errid_PROVIDERECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errid_PROVIDERECM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''id_RAPPRLEGALE_PROVIDERECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_RAPPRLEGALE_PROVIDERECM As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''errid_RAPPRLEGALE_PROVIDERECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errid_RAPPRLEGALE_PROVIDERECM As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''id_DISCIPLINAs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id_DISCIPLINAs As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''errid_DISCIPLINAs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errid_DISCIPLINAs As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ecm2_COD_EVE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ecm2_COD_EVE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errecm2_COD_EVE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errecm2_COD_EVE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ecm2_NUM_CRED control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ecm2_NUM_CRED As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errecm2_NUM_CRED control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errecm2_NUM_CRED As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ecm2_CREDITILETTERE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ecm2_CREDITILETTERE As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''errecm2_CREDITILETTERE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents errecm2_CREDITILETTERE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkCreate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCreate As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''cnfCreate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cnfCreate As Global.AjaxControlToolkit.ConfirmButtonExtender
    
    '''<summary>
    '''lblGlobalError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGlobalError As Global.System.Web.UI.WebControls.Label
End Class
