'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SchedaPartecipante
    
    '''<summary>
    '''lblTitolo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitolo1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTitolo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitolo2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''updButtons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updButtons As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''sezioneIncarico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sezioneIncarico As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lnkLetteraIncarico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLetteraIncarico As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''sezioneAttEcm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sezioneAttEcm As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lnkAttestatoECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAttestatoECM As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkAttestatoPART control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAttestatoPART As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkClose As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''updISCRITTI_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updISCRITTI_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''frmISCRITTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmISCRITTI As Global.Softailor.Web.UI.DbForms.StlFormView
    
    '''<summary>
    '''tabContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabContainer As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''pnlRecapiti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRecapiti As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''updRecapiti_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updRecapiti_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''grdRecapiti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdRecapiti As Global.Softailor.Web.UI.DbForms.StlGridView
    
    '''<summary>
    '''updRecapiti_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updRecapiti_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''frmRecapiti control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmRecapiti As Global.Softailor.Web.UI.DbForms.StlFormView
    
    '''<summary>
    '''pnlQuote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlQuote As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''updQUOTE_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updQUOTE_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''grdQUOTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdQUOTE As Global.Softailor.Web.UI.DbForms.StlGridView
    
    '''<summary>
    '''updQUOTE_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updQUOTE_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''frmQUOTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmQUOTE As Global.Softailor.Web.UI.DbForms.StlFormView
    
    '''<summary>
    '''pnlVociSpesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlVociSpesa As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''updCOSTIRICAVI_ISCRITTI_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updCOSTIRICAVI_ISCRITTI_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''grdCOSTIRICAVI_ISCRITTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCOSTIRICAVI_ISCRITTI As Global.Softailor.Web.UI.DbForms.StlGridView
    
    '''<summary>
    '''updCOSTIRICAVI_ISCRITTI_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updCOSTIRICAVI_ISCRITTI_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''frmCOSTIRICAVI_ISCRITTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmCOSTIRICAVI_ISCRITTI As Global.Softailor.Web.UI.DbForms.StlFormView
    
    '''<summary>
    '''pnlInOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInOut As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''updACCESSIISCRITTI_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updACCESSIISCRITTI_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''grdACCESSIISCRITTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdACCESSIISCRITTI As Global.Softailor.Web.UI.DbForms.StlGridView
    
    '''<summary>
    '''sdsACCESSIISCRITTI_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsACCESSIISCRITTI_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''updACCESSIISCRITTI_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updACCESSIISCRITTI_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''frmACCESSIISCRITTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmACCESSIISCRITTI As Global.Softailor.Web.UI.DbForms.StlFormView
    
    '''<summary>
    '''sdsACCESSIISCRITTI_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsACCESSIISCRITTI_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''updDettaglioTempi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updDettaglioTempi As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''phdDettaglioTempi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phdDettaglioTempi As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''pnlStoricoModifiche control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStoricoModifiche As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''updStorico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updStorico As Global.Softailor.Web.UI.DbForms.StlUpdatePanel
    
    '''<summary>
    '''grdStorico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdStorico As Global.Softailor.Web.UI.DbForms.StlGridView
    
    '''<summary>
    '''sdsStorico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsStorico As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''sdsISCRITTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsISCRITTI As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''sdsQUOTE_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsQUOTE_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''sdsQUOTE_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsQUOTE_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''sdsRecapiti_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsRecapiti_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''sdsRECAPITI_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsRECAPITI_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''sdsCOSTIRICAVI_ISCRITTI_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsCOSTIRICAVI_ISCRITTI_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''sdsCOSTIRICAVI_ISCRITTI_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsCOSTIRICAVI_ISCRITTI_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
    
    '''<summary>
    '''sdsac_CATEGORIAECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_CATEGORIAECM As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsac_STATOISCRIZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_STATOISCRIZIONE As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsac_STATOECM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_STATOECM As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsac_STATOQUESTIONARIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_STATOQUESTIONARIO As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsac_CATEGORIALAVORATIVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_CATEGORIALAVORATIVA As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsac_TITOLO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_TITOLO As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsid_QUOTAISCRIZIONE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsid_QUOTAISCRIZIONE As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsid_IVA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsid_IVA As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsac_TIPOPAG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_TIPOPAG As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsac_TIPORECAPITO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_TIPORECAPITO As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsid_DELIBERA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsid_DELIBERA As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsac_VOCESPESARICAVO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_VOCESPESARICAVO As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''sdsid_ALBO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsid_ALBO As Global.System.Web.UI.WebControls.SqlDataSource
End Class
