'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SelezioneEvento

    '''<summary>
    '''updRecent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updRecent As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdRecent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdRecent As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsRecent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsRecent As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''pnlNuovoEvento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNuovoEvento As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''updEVENTI_src control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updEVENTI_src As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''srcEVENTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents srcEVENTI As Global.Softailor.Web.UI.DbForms.StlSearchForm

    '''<summary>
    '''updEVENTI_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updEVENTI_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdEVENTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdEVENTI As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''sdsEVENTI_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsEVENTI_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource
End Class
