'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SetupAttestatoECM

    '''<summary>
    '''lnkAttestatoTest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAttestatoTest As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkAttestatoTestDocente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAttestatoTestDocente As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''updEVENTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updEVENTI As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''frmEVENTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmEVENTI As Global.Softailor.Web.UI.DbForms.StlFormView

    '''<summary>
    '''sdsEVENTI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsEVENTI As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''sdsecm2_id_ELEME_PROVIDER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsecm2_id_ELEME_PROVIDER As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsecm2_id_ELEME_FIRMA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsecm2_id_ELEME_FIRMA As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsecm2_id_ELEME_FIRMA2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsecm2_id_ELEME_FIRMA2 As Global.System.Web.UI.WebControls.SqlDataSource
End Class
