'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SpeseRicaviEvento

    '''<summary>
    '''updCOSTIRICAVI_EVENTO_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updCOSTIRICAVI_EVENTO_g As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''grdCOSTIRICAVI_EVENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdCOSTIRICAVI_EVENTO As Global.Softailor.Web.UI.DbForms.StlGridView

    '''<summary>
    '''updCOSTIRICAVI_EVENTO_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updCOSTIRICAVI_EVENTO_f As Global.Softailor.Web.UI.DbForms.StlUpdatePanel

    '''<summary>
    '''frmCOSTIRICAVI_EVENTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmCOSTIRICAVI_EVENTO As Global.Softailor.Web.UI.DbForms.StlFormView

    '''<summary>
    '''sdsCOSTIRICAVI_EVENTO_g control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsCOSTIRICAVI_EVENTO_g As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''sdsCOSTIRICAVI_EVENTO_f control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsCOSTIRICAVI_EVENTO_f As Global.Softailor.Web.UI.DbForms.StlSqlDataSource

    '''<summary>
    '''sdsac_TIPOPAG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_TIPOPAG As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsid_DELIBERA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsid_DELIBERA As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sdsac_VOCESPESARICAVO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdsac_VOCESPESARICAVO As Global.System.Web.UI.WebControls.SqlDataSource
End Class
